name: publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: [v1.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno }}

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Modify jsr config
        uses: maxgfr/github-change-json@main
        with:
          key: version
          value: ${{steps.get_tag_version.outputs.TAG_VERSION}}
          path: ./jsr.json

      - name: publish
        run: deno task publish
